FROM python:3.11-slim

WORKDIR /app

# Nâng cấp pip lên phiên bản mới nhất
RUN pip install --upgrade pip

# Cài đặt dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Sao chép mã nguồn
COPY . .

EXPOSE 5002

# Chạy ứng dụng
CMD ["python", "app.py"]